config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :sales
  end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  has_many :product_sales
  has_many :sales, through: :product_sales

  def on_sale?(user = nil)
    return true if user && product_sales.active.exists?(user: user)
    product_sales.active.exists?(user: nil)
  end

  def active_sale(user = nil)
    @active_sale ||= if user && product_sales.active.exists?(user: user)
                       product_sales.active.where(user: user).first
                     else
                       product_sales.active.where(user: nil).first
                     end
  end
end

app/models/spree/product_sale.rb
module Spree
  class ProductSale < ActiveRecord::Base
    belongs_to :product
    belongs_to :sale
    belongs_to :user

    validates_presence_of :product_id, :sale_id

    scope :active, -> { where("? >= start_date AND ? < end_date", Time.zone.now, Time.zone.now) }
  end
end

app/models/spree/products_taxon.rb
module Spree
  class ProductsTaxon < ActiveRecord::Base
  end
end

app/models/spree/sale.rb
module Spree
  class Sale < ActiveRecord::Base
    has_many :product_sales, dependent: :destroy

    has_many :sale_taxons, dependent: :destroy
    has_many :taxons, through: :sale_taxons
    has_many :sale_products, dependent: :destroy
    has_many :products, through: :sale_products
    has_many :sale_user_groups, dependent: :destroy
    has_many :user_groups, through: :sale_user_groups
    has_many :sale_users, dependent: :destroy
    has_many :users, through: :sale_users

    accepts_nested_attributes_for :taxons, allow_destroy: true
    accepts_nested_attributes_for :products, allow_destroy: true
    accepts_nested_attributes_for :user_groups, allow_destroy: true
    accepts_nested_attributes_for :users, allow_destroy: true

    enum sale_type: [:percent, :fixed]

    validates_presence_of :name, :start_date, :amount, :sale_type

    def active?
      return false if Time.zone.now < start_date
      return false if end_date && Time.zone.now > end_date
      true
    end
  end
end

app/models/spree/sale_product.rb
class Spree::SaleProduct < ActiveRecord::Base
  belongs_to :sale
  belongs_to :product
end

app/models/spree/sale_taxon.rb
class Spree::SaleTaxon < ActiveRecord::Base
  belongs_to :sale
  belongs_to :taxon
end

app/models/spree/sale_user.rb
class Spree::SaleUser < ActiveRecord::Base
  belongs_to :sale
  belongs_to :user
end

app/models/spree/sale_user_group.rb
class Spree::SaleUserGroup < ActiveRecord::Base
  belongs_to :sale
  belongs_to :user_group
end

app/models/spree/user_decorator.rb
Spree::User.class_eval do
  def self.current
    Thread.current[:user]
  end

  def self.current=(user)
    Thread.current[:user] = user
  end
end

app/models/spree/variant_decorator.rb
Spree::Variant.class_eval do
  alias_method :orig_price_in, :price_in

  def price_in(currency)
    return orig_price_in(currency) unless sale_price
    Spree::Price.new(variant_id: self.id, amount: sale_price, currency: currency)
  end

  def sale_price
    @sale_price ||= count_sale_price
  end

  def count_sale_price
    product_sale = product.active_sale(Spree::User.current)
    return nil if product_sale.nil?

    if product_sale.sale.percent?
      return price - (price * product_sale.sale.amount)
    else
      return price - product_sale.sale.amount
    end
  end
end

app/controllers/application_controller_decorator.rb
ApplicationController.class_eval do
  before_filter :set_current_user

  def set_current_user
    Spree::User.current = spree_current_user
  end
end

app/controllers/spree/admin/sales_controller.rb
module Spree
  module Admin
    class SalesController < Spree::Admin::ResourceController
      before_action :prepare_array_params, only: [:create, :update]

      def index
        @sales = Spree::Sale.all
      end

      def new
        @sale = Spree::Sale.new
      end

      def create
        @sale = SaleCreator.create(sale_params)
        respond_with @sale, location: polymorphic_url([:admin, :sales])
      end

      def edit
        set_sale
      end

      def update
        set_sale
        @sale = SaleCreator.create(sale_params, @sale)
        respond_with @sale, location: polymorphic_url([:admin, :sales])
      end

      private

      def set_sale
        @sale = Spree::Sale.find(params[:id])
      end

      def sale_params
        params.require(:sale).permit(:name, :description, :amount, :sale_type,
                                     :start_date, :end_date,
                                     taxon_ids: [], product_ids: [],
                                     user_group_ids: [], user_ids: [])
      end

      def prepare_array_params
        [:taxon_ids, :product_ids, :user_group_ids, :user_ids].each do |key|
          if params[:sale][key].present?
            params[:sale][key] = params[:sale][key].split(',')
          else
            params[:sale][key] = []
          end
        end
      end
    end
  end
end

app/views/spree/admin/sales/_form.html.slim
= simple_form_for [:admin, sale] do |f|
  .row
    .col-md-12
      = f.input :name
  .row
    .col-md-12
      = f.input :description
  .row
    .col-md-6
      = f.input :start_date, as: :string, input_html: { class: 'datepicker', value: datepicker_field_value(@sale.start_date) }
    .col-md-6
      = f.input :end_date, as: :string, input_html: { class: 'datepicker', value: datepicker_field_value(@sale.end_date) }
  .row
    .col-md-6
      = f.input :sale_type, collection: Spree::Sale.sale_types.keys.map {|sale| [sale.titleize, sale]}
    .col-md-6
      = f.input :amount

  .row
    .col-md-6
      = f.label :taxon_ids, 'Taxons'
      = f.hidden_field :taxon_ids, value: @sale.taxon_ids.join(',')
        - if @sale.taxons.any?
          ul.text_list
            - sale.taxons.each do |taxon|
             li = taxon.name
        - else
          .alert.alert-info = Spree.t(:no_resource_found, resource: :taxons)

    .col-md-6
      = f.label :product_ids, 'Products'
      = f.hidden_field :product_ids, value: @sale.product_ids.join(','), class: 'product_picker'

  .row
    .col-md-6
      = f.label :user_group_ids, 'User groups'
      = f.hidden_field :user_group_ids, value: @sale.user_group_ids.join(','), class: 'user_group_picker'

    .col-md-6
      = f.label :user_ids, 'Users'
      = f.hidden_field :user_ids, value: @sale.user_ids.join(','), class: 'user_picker'

  - if sale.persisted?
    = render 'spree/admin/shared/edit_resource_links'
  - else
    = render 'spree/admin/shared/new_resource_links'

app/views/spree/admin/sales/edit.html.slim
= render 'spree/admin/shared/error_messages', target: @sale

- content_for :page_title, 'Edit Sale'

= render 'form', sale: @sale

app/views/spree/admin/sales/index.html.slim
- content_for :page_title, 'Sales'

- content_for :page_actions do
  = button_link_to t("admin.new_sale"), new_admin_sale_path, class: "btn-success", icon: 'add', id: 'admin_new_sale'

- if @sales.any?
  table.table.sortable id="listing_companies"
    thead
      tr
        th Name
        th.actions
    tbody
      - @sales.each do |sale|
        tr id="#{ spree_dom_id sale }" class="#{ cycle('odd', 'even') }"
            td = link_to sale.name, edit_admin_sale_path(sale)
            td.actions.actions-2.text-right
              = link_to_edit sale, no_text: true, class: 'edit' if can?(:edit, sale)
              = link_to_delete sale, no_text: true if can?(:delete, sale)
- else
  .alert.alert-info.no-objects-found
    = Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Sale))
    = link_to Spree.t(:add_one), new_admin_sale_path

app/views/spree/admin/sales/new.html.slim
= render 'spree/admin/shared/error_messages', target: @sale

- content_for :page_title, 'New Sale'

= render 'form', sale: @sale